services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopease_php
    container_name: shopease_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - shopease

  webserver:
    image: nginx:alpine
    container_name: shopease_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shopease



  db:
    image: mysql:5.7
    container_name: shopease_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shopease

  redis:
    image: redis:alpine
    container_name: shopease_redis
    restart: unless-stopped
    networks:
      - shopease

networks:
  shopease:
    driver: bridge

volumes:
  dbdata:
    driver: local
