'paths' => ['api/*'],
'allowed_methods' => ['*'],
'allowed_origins' => ['http://165.22.215.178'],
'allowed_headers' => ['*'],
'exposed_headers' => [],
'max_age' => 0,
'supports_credentials' => false,
