name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopease
          MYSQL_USER: shopease
          MYSQL_PASSWORD: shopease
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo_mysql, redis
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=1G
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate

    - name: Run tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        args: compute droplet create --region nyc3 --image docker-20-04 --size s-1vcpu-1gb --ssh-keys ${{ secrets.DIGITALOCEAN_SSH_KEY_ID }} --tag-name shopease --wait --enable-backups --enable-monitoring --user-data-file deploy.sh
